version: 0.4
name: 
  latency-rate-limited-10000_qps-memtier_benchmark-3Mkeys-load-string-with-512B-values
description: Runs memtier_benchmark, for a keyspace length of 3M keys loading STRINGs
  in which the value has a data size of 512 Bytes, with 650 clients running sequential
  SET commands. Rate limited to 10000 ops/sec.
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 0
  resources:
    requests:
      memory: 3g
tested-commands:
- set
redis-topologies:
- oss-standalone
- oss-standalone-02-io-threads
- oss-standalone-04-io-threads
- oss-standalone-08-io-threads
- oss-standalone-16-io-threads
- oss-standalone-32-io-threads
- oss-standalone-64-io-threads
build-variants:
- gcc:8.5.0-amd64-debian-buster-default
- dockerhub
clientconfig:
  run_image: redislabs/memtier_benchmark:edge
  tool: memtier_benchmark
  arguments: "\"--data-size\" \"512\" --ratio 1:0 --key-pattern P:P --key-minimum=1
    --key-maximum 3000000 --test-time 180 -c 50 -t 13 --hide-histogram --rate-limiting
    15"
  resources:
    requests:
      cpus: '13'
      memory: 2g

tested-groups:
- string
priority: 17
