version: 0.4
name: 
  latency-rate-limited-10000_qps-memtier_benchmark-10Mkeys-load-hash-5-fields-with-1000B-values-pipeline-10
description: Runs memtier_benchmark, for a keyspace length of 10M keys loading HASHES
  with 5 fields each. Each field value has a data size of 1000 Bytes. Rate limited
  to 10000 ops/sec.
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 0
  resources:
    requests:
      memory: 52g
tested-commands:
- hset
redis-topologies:
- oss-standalone
build-variants:
- gcc:8.5.0-amd64-debian-buster-default
- dockerhub
clientconfig:
  run_image: redislabs/memtier_benchmark:edge
  tool: memtier_benchmark
  arguments: "--test-time 180 \"--pipeline\" \"10\" \"--data-size\" \"1000\" --command
    \"HSET __key__ field1 __data__ field2 __data__ field3 __data__ field4 __data__
    field5 __data__\" \"--command-key-pattern\" \"P\" --key-minimum=1 --key-maximum
    10000000 -c 50 -t 4 --hide-histogram --rate-limiting 50"
  resources:
    requests:
      cpus: '4'
      memory: 2g

tested-groups:
- hash
priority: 5
