version: 0.4
name: memtier_benchmark-100Kkeys-hash-hgetall-50-fields-100B-values
description: Runs memtier_benchmark, for a keyspace length of 1M keys pre-loading
  HASHes in which the value has a data size of 10 Bytes. After pre-loading the data
  it issues HGETALL command.
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 100000
  preload_tool:
    run_image: redislabs/memtier_benchmark:edge
    tool: memtier_benchmark
    arguments: '"--data-size" "100" --command "HSET __key__ field:1 __data__ field:2
      __data__ field:3 __data__ field:4 __data__ field:5 __data__ field:6 __data__
      field:7 __data__ field:8 __data__ field:9 __data__ field:10 __data__ field:11
      __data__ field:12 __data__ field:13 __data__ field:14 __data__ field:15 __data__
      field:16 __data__ field:17 __data__ field:18 __data__ field:19 __data__ field:20
      __data__ field:21 __data__ field:22 __data__ field:23 __data__ field:24 __data__
      field:25 __data__ field:26 __data__ field:27 __data__ field:28 __data__ field:29
      __data__ field:30 __data__ field:31 __data__ field:32 __data__ field:33 __data__
      field:34 __data__ field:35 __data__ field:36 __data__ field:37 __data__ field:38
      __data__ field:39 __data__ field:40 __data__ field:41 __data__ field:42 __data__
      field:43 __data__ field:44 __data__ field:45 __data__ field:46 __data__ field:47
      __data__ field:48 __data__ field:49 __data__ field:50 __data__" --command-key-pattern="P"
      --key-minimum=1 --key-maximum 1000000 -n 500 -c 50 -t 4 --hide-histogram'
  resources:
    requests:
      memory: 2g
  dataset_name: 100Kkeys-hash-50-fields-100B-size
  dataset_description: This dataset contains 100,000 hash keys, each with 50 fields
    and each field has a data size of 100 bytes.
tested-groups:
- hash
tested-commands:
- hgetall
redis-topologies:
- oss-standalone
build-variants:
- gcc:15.2.0-amd64-debian-bookworm-default
- gcc:15.2.0-arm64-debian-bookworm-default
- dockerhub
clientconfig:
  run_image: redislabs/memtier_benchmark:edge
  tool: memtier_benchmark
  arguments: ' --command "HGETALL __key__" --command-key-pattern="R" --key-minimum=1
    --key-maximum 100000 --test-time 120 -c 50 -t 4 --hide-histogram'
  resources:
    requests:
      cpus: '4'
      memory: 2g
priority: 96
