version: 0.4
name: memtier_benchmark-1Mkeys-load-string-with-20KiB-values
description: Runs memtier_benchmark, for a keyspace length of 1M keys loading STRINGs
  in which the value has a data size of 20K Bytes.
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 0
  resources:
    requests:
      memory: 12g
tested-commands:
- set
redis-topologies:
- oss-standalone
build-variants:
- gcc:15.2.0-amd64-debian-bookworm-default
- gcc:15.2.0-arm64-debian-bookworm-default
- dockerhub
clientconfig:
  run_image: redislabs/memtier_benchmark:edge
  tool: memtier_benchmark
  arguments: '"--data-size" "20000" --ratio 1:0 --key-pattern P:P --key-minimum=1
    --key-maximum 1000000 --test-time 180 -c 50 -t 4 --hide-histogram'
  resources:
    requests:
      cpus: '4'
      memory: 2g
  scalability:
    mode: '1:1'
    max_processes: 21
tested-groups:
- string
priority: 17
