version: 0.4
name: memtier_benchmark-100Kkeys-load-hash-1-fields-with-10B-values-short-expiration
description: Runs memtier_benchmark, for a keyspace length of 100K keys loading HASHES
  with 1 fields each. Each field value has a data size of 10 Bytes and has really short
  expiration, meaning expiration is expected to affect performance after 1st second.
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 0
  resources:
    requests:
      memory: 6g
tested-groups:
- hash
tested-commands:
- hsetex
redis-topologies:
- oss-standalone
build-variants:
- gcc:15.2.0-amd64-debian-bookworm-default
- gcc:15.2.0-arm64-debian-bookworm-default
- dockerhub
clientconfig:
  run_image: redislabs/memtier_benchmark:edge
  tool: memtier_benchmark
  arguments: --test-time 120 --distinct-client-seed "--data-size" "10" --command "HSETEX 
    __key__ EX 1 FIELDS 1 
    field:1 __data__ "
    --command-key-pattern="R" --key-minimum=1 --key-maximum 100000 -c 50 -t 4 --hide-histogram
  resources:
    requests:
      cpus: '4'
      memory: 2g
priority: 5
