version: 0.4
name: memtier_benchmark-100Kkeys-load-hash-5-fields-with-1000B-values-expiration
description: Runs memtier_benchmark, for a keyspace length of 100K keys loading HASHES
  with 5 field each. Each field value has a data size of 1000 Bytes and has expiration,
  and the encoding is hashtable.
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 0
  resources:
    requests:
      memory: 6g
tested-groups:
- hash
tested-commands:
- hsetex
redis-topologies:
- oss-standalone
build-variants:
- gcc:15.2.0-amd64-debian-bookworm-default
- gcc:15.2.0-arm64-debian-bookworm-default
- dockerhub
clientconfig:
  run_image: redislabs/memtier_benchmark:edge
  tool: memtier_benchmark
  arguments: --test-time 120 --distinct-client-seed "--data-size" "1000" --command "HSETEX 
    __key__ EX 60 FIELDS 5 
    field:1 __data__ field:2 __data__ field:3 __data__ field:4 __data__ field:5
    __data__ "
    --command-key-pattern="R" --key-minimum=1 --random-data --key-maximum 100000 -c 50 -t 4 --hide-histogram
  resources:
    requests:
      cpus: '4'
      memory: 2g
priority: 5
