version: 0.4
name: memtier_benchmark-1Mkeys-load-string-with-10B-values-pipeline-100-nokeyprefix
description: memtier_benchmark, 1M keys, string SET, 10B value size, pipeline=100,
  no key prefix
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 0
  resources:
    requests:
      memory: 1g
tested-groups:
- string
tested-commands:
- set
redis-topologies:
- oss-standalone
- oss-cluster-3-primaries
clientconfig:
  run_image: redislabs/memtier_benchmark:edge
  tool: memtier_benchmark
  arguments: '"--data-size" "10" --command "SET __key__ __data__" --command-key-pattern="R"
    --key-prefix="" -c 50 -t 2 --pipeline 100 --hide-histogram --test-time 180'
  resources:
    requests:
      cpus: '3'
      memory: 2g
priority: 33
