version: 0.4
name: memtier_benchmark-1Mkeys-load-stream-5-fields-with-100B-values
description: Runs memtier_benchmark, for a keyspace length of 1M keys loading STREAMs
  in which the 5 field values have a data size of 100 Bytes.
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 0
  resources:
    requests:
      memory: 8g
tested-commands:
- xadd
redis-topologies:
- oss-standalone
build-variants:
- gcc:15.2.0-amd64-debian-bookworm-default
- gcc:15.2.0-arm64-debian-bookworm-default
- dockerhub
clientconfig:
  run_image: redislabs/memtier_benchmark:edge
  tool: memtier_benchmark
  arguments: '"--data-size" "100" --command "XADD __key__ MAXLEN ~ 5 * field __data__
    field __data__ field __data__ field __data__ field __data__" --command-key-pattern="P"
    --key-minimum=1 --key-maximum 1000000 --test-time 180 -c 50 -t 4 --hide-histogram'
  resources:
    requests:
      cpus: '4'
      memory: 2g
tested-groups:
- stream
priority: 66
