version: 0.4
name: memtier_benchmark-10Mkeys-load-hash-5-fields-with-100B-values
description: Runs memtier_benchmark, for a keyspace length of 10M keys loading HASHES
  with 5 fields each. Each field value has a data size of 100 Bytes.
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 0
  resources:
    requests:
      memory: 9g
tested-commands:
- hset
redis-topologies:
- oss-standalone
build-variants:
- gcc:15.2.0-amd64-debian-bookworm-default
- gcc:15.2.0-arm64-debian-bookworm-default
- dockerhub
clientconfig:
  run_image: redislabs/memtier_benchmark:edge
  tool: memtier_benchmark
  arguments: --test-time 180 "--data-size" "100" --command "HSET __key__ field1 __data__
    field2 __data__ field3 __data__ field4 __data__ field5 __data__" --command-key-pattern="P"
    --key-minimum=1 --key-maximum 10000000 -c 50 -t 4 --hide-histogram
  resources:
    requests:
      cpus: '4'
      memory: 2g
tested-groups:
- hash
priority: 5
