version: 0.4
name: memtier_benchmark-1Mkeys-load-string-with-100B-values
description: Runs memtier_benchmark, for a keyspace length of 1M keys loading STRINGs in which the value has a data size of 100 Bytes.
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 0
  resources:
    requests:
      memory: 12g
tested-commands:
- set
redis-topologies:
- oss-standalone
- oss-cluster-03-primaries
- oss-cluster-05-primaries
- oss-cluster-09-primaries
- oss-cluster-15-primaries
- oss-cluster-21-primaries
build-variants:
- gcc:8.5.0-amd64-debian-buster-default
clientconfig:
  run_image: redislabs/memtier_benchmark:edge
  tool: memtier_benchmark
  arguments: '"--data-size" "100" --ratio 1:0 --key-pattern P:P --key-minimum=1 --key-maximum 1000000 --test-time 180 -c 50 -t 4 --hide-histogram'
  resources:
    requests:
      cpus: '4'
      memory: 2g
  scalability:
    mode: '1:1'
    max_processes: 21

tested-groups:
- string
priority: 17
